name: Sync Node base image to GitHub Container Registry

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * 0' # Every monday

permissions:
  packages: write
  contents: read

jobs:
  sync-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [ "22.2-bookworm-slim", "22.2-bookworm" ]

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update ghcr.io/${{ github.repository_owner }}/node:${{ matrix.tag }}
        run: |
          docker pull docker.io/library/node:${{ matrix.tag }}
          docker tag docker.io/library/node:${{ matrix.tag }} ghcr.io/${{ github.repository_owner }}/node:${{ matrix.tag }}
          docker push ghcr.io/${{ github.repository_owner }}/node:${{ matrix.tag }}
