name: Sync Node base image to GitHub Container Registry

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * 0' # Every monday

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write
      id-token: write
      security-events: write
    strategy:
      matrix:
        include:
          - BASE_IMAGE: "node:22.8-bookworm-slim"
            TAG_VERSION: "22.8"
          - BASE_IMAGE: "node:22.7-bookworm-slim"
            TAG_VERSION: "22.7"
          - BASE_IMAGE: "node:22.6-bookworm-slim"
            TAG_VERSION: "22.6"
          - BASE_IMAGE: "node:20.17-bookworm-slim"
            TAG_VERSION: "20.17"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' || github.event_name == 'schedule' }}
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/node:${{ matrix.TAG_VERSION }}
          build-args: |
            BASE_IMAGE=${{ matrix.BASE_IMAGE }}
          cache-from: type=gha,scope=${{ matrix.TAG_VERSION }}
          cache-to: type=gha,mode=max,scope=${{ matrix.TAG_VERSION }}
