name: Delete old container images

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Whether to perform a dry run
        default: false
  #schedule:
  #  - cron: '8 0 * * *'

permissions:
  packages: write
  contents: read

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ghcr.io/${{ github.repository_owner }}/node
          cut-off: 4w
          dry-run: ${{ github.event.inputs.dry-run }}